export const featuredProducts = [
  {
    slug: "celeste-bow-earrings",
    name: "Celeste Bow Earrings",
    price: "₹1,299",
    material: "Gold plated",
    image: "/Product/img.jpg",
    category: "earrings",
    description: "A delicate bow and crystal earring set made to bring a soft finish to everyday looks.",
    badges: ["New"],
  },
  {
    slug: "daisy-charm-anklet",
    name: "Daisy Charm Anklet",
    price: "₹1,099",
    material: "18k gold plated",
    image: "/Product/img2.jpg",
    category: "anklets",
    description: "A light floral charm anklet designed for easy movement and effortless daily styling.",
    badges: ["Bestseller"],
  },
  {
    slug: "meadow-charm-necklace",
    name: "Meadow Charm Necklace",
    price: "₹1,499",
    material: "18k gold plated",
    image: "/Product/Charm Necklace.jpg",
    category: "necklaces",
    description: "A polished floral charm necklace that layers beautifully or stands gracefully on its own.",
    badges: ["Limited"],
  },
  {
    slug: "emerald-dial-watch",
    name: "Emerald Dial Watch",
    price: "₹2,499",
    material: "Stainless steel",
    image: "/Product/watch.jpg",
    category: "watches",
    description: "A refined emerald dial watch with a jewellery-inspired bracelet silhouette.",
    badges: ["Bestseller"],
  },
];

export const products = [
  ...featuredProducts,
  {
    slug: "golden-drop-anklet",
    name: "Golden Drop Anklet",
    price: "₹899",
    image: "/Product/Anklets.jpg",
    category: "kids",
    description: "A delicate gold anklet finished with softly moving drop charms.",
  },
  {
    slug: "colour-charm-anklet",
    name: "Colour Charm Anklet",
    price: "₹949",
    image: "/Product/Anklets2.jpg",
    category: "kids",
    description: "A fine anklet dotted with playful coloured charms.",
  },
  {
    slug: "luna-disc-anklet",
    name: "Luna Disc Anklet",
    price: "₹899",
    image: "/Product/Anklets3.jpg",
    category: "kids",
    description: "A light chain anklet with polished circular charms.",
  },
  {
    slug: "tiny-heart-anklet",
    name: "Tiny Heart Anklet",
    price: "₹949",
    image: "/Product/Anklets4.jpg",
    category: "kids",
    description: "A graceful everyday anklet with petite heart details.",
  },
  { slug: "daisy-chain-anklet", name: "Kids Daisy Chain Anklet", price: "₹999", image: "/Product/Anklets5.jpg", category: "kids", description: "A floral kids anklet designed for an easy everyday shine." },
  { slug: "minimal-charm-bracelets", name: "Minimal Charm Bracelets", price: "₹1,199", image: "/Product/Bracelet.jpg", category: "bracelets", description: "Four slim charm bracelets for wearing alone or together." },
  { slug: "triple-heart-necklace", name: "Triple Heart Necklace", price: "₹1,499", image: "/Product/Charm Necklace  2.jpg", category: "necklaces", description: "A fine chain necklace set with three crystal heart charms." },
  { slug: "crystal-heart-necklace", name: "Crystal Heart Necklace", price: "₹1,399", image: "/Product/Charm Necklace2.jpg", category: "necklaces", description: "A polished heart necklace with a bright crystal centre." },
  { slug: "sunlit-frame-necklace", name: "Sunlit Frame Necklace", price: "₹1,299", image: "/Product/Charm Necklace3.jpg", category: "necklaces", description: "A refined framed pendant on a delicate gold chain." },
  { slug: "ivory-frame-necklace", name: "Ivory Frame Necklace", price: "₹1,299", image: "/Product/Charm Necklace4.jpg", category: "necklaces", description: "An ivory centre pendant framed with fine golden detail." },
  { slug: "garden-drop-necklace", name: "Garden Drop Necklace", price: "₹1,499", image: "/Product/Charm Necklace5.jpg", category: "necklaces", description: "A delicate botanical necklace with softly spaced charms." },
  { slug: "tiny-bow-necklace", name: "Tiny Bow Necklace", price: "₹1,249", image: "/Product/Charm Necklace6.jpg", category: "necklaces", description: "A minimal necklace centred with a petite bow charm." },
  { slug: "tulip-charm-necklace", name: "Tulip Charm Necklace", price: "₹1,299", image: "/Product/Charm.jpg", category: "necklaces", description: "A colourful tulip charm necklace for gentle everyday styling." },
  { slug: "daisy-garden-bangle", name: "Daisy Garden Bangle", price: "₹1,399", image: "/Product/img10.jpg", category: "bangles", description: "An openwork gold bangle shaped with a row of daisies." },
  { slug: "crystal-link-bangle", name: "Crystal Link Bangle", price: "₹1,499", image: "/Product/img11.jpg", category: "bangles", description: "A slender link bangle finished with bright crystal accents." },
  { slug: "botanical-statement-bangle", name: "Botanical Statement Bangle", price: "₹1,299", image: "/Product/img12.jpg", category: "bangles", description: "A sculptural floral bangle with an airy botanical silhouette." },
  { slug: "feather-cuff-bangle", name: "Feather Cuff Bangle", price: "₹1,349", image: "/Product/img13.jpg", category: "bangles", description: "A polished open cuff inspired by overlapping feathers." },
  { slug: "midnight-star-bangle", name: "Midnight Star Bangle", price: "₹1,399", image: "/Product/img14.jpg", category: "bangles", description: "A slim celestial bangle with deep blue star details." },
  { slug: "sculpted-knot-bangle", name: "Sculpted Knot Bangle", price: "₹1,249", image: "/Product/img15.jpg", category: "bangles", description: "A fluid open bangle finished with a modern sculpted knot." },
  { slug: "silverline-gold-bangle", name: "Silverline Gold Bangle", price: "₹1,599", image: "/Product/img16.jpg", category: "bangles", description: "A sleek gold bangle crossed with a crystal silver line." },
  { slug: "aurelia-statement-ring", name: "Aurelia Statement Ring", price: "₹1,249", image: "/Product/img17.jpg", category: "rings", description: "A sculptural gold ring with a softly folded form." },
  { slug: "stacked-line-rings", name: "Stacked Line Rings", price: "₹1,199", image: "/Product/img18.jpg", category: "rings", description: "A coordinated ring stack made from clean golden lines." },
  { slug: "tiny-bow-ring", name: "Tiny Bow Ring", price: "₹999", image: "/Product/img19.jpg", category: "rings", description: "A delicate bow ring with a light, playful finish." },
  { slug: "rose-dial-watch-set", name: "Rose Dial Watch Set", price: "₹2,799", image: "/Product/img20.jpg", category: "watches", description: "A blush watch paired with polished charm bracelets." },
  { slug: "jewellery-gift-edit", name: "Jewellery Gift Edit", price: "₹2,999", image: "/Product/img21.jpg", category: "bangles", description: "A curated gift box of rings and a polished gold bangle." },
  { slug: "rose-charm-watch", name: "Rose Charm Watch", price: "₹2,699", image: "/Product/img22.jpg", category: "watches", description: "A blush dial watch styled with delicate charm bracelets." },
  { slug: "blush-link-watch", name: "Blush Link Watch", price: "₹2,899", image: "/Product/img23.jpg", category: "watches", description: "A blush dial watch with a bright jewellery inspired strap." },
  { slug: "mira-necklace-bracelet-combo", name: "Mira Necklace & Bracelet Combo", price: "₹1,999", image: "/Product/img3.jpg", category: "necklaces", description: "A coordinated layered necklace and butterfly bracelet set with an elegant golden finish." },
  { slug: "onyx-disc-bangle", name: "Onyx Disc Bangle", price: "₹1,199", image: "/Product/img5.jpg", category: "bangles", description: "A polished bangle punctuated with black and pearl discs." },
  { slug: "daisy-chain-bangle", name: "Daisy Chain Bangle", price: "₹1,399", image: "/Product/img6.jpg", category: "bangles", description: "A floral gold bangle made from linked daisy forms." },
  { slug: "colour-stone-bangle", name: "Colour Stone Bangle", price: "₹1,499", image: "/Product/img7.jpg", category: "bangles", description: "A slim gold bangle set with colourful square stones." },
  { slug: "crystal-daisy-bangle", name: "Crystal Daisy Bangle", price: "₹1,499", image: "/Product/img8.jpg", category: "bangles", description: "A bright daisy bangle with a crystal detailed centre." },
  { slug: "midnight-flower-bangle", name: "Midnight Flower Bangle", price: "₹1,449", image: "/Product/img9.jpg", category: "bangles", description: "A polished bangle centred with a deep floral stone." },
  { slug: "classic-necklace-bracelet-set", name: "Classic Necklace & Bracelet Set", price: "₹2,399", image: "/Product/Necklace & Bracelet Combo Set.jpg", category: "necklaces", description: "A matching pendant necklace and bracelet set." },
  { slug: "tulip-necklace-bracelet-set", name: "Tulip Necklace & Bracelet Set", price: "₹2,499", image: "/Product/Our Tulip Necklace & Bracelet Set.jpg", category: "necklaces", description: "A delicate tulip necklace with its matching bracelet." },
  { slug: "everyday-layering-necklaces", name: "Everyday Layering Necklaces", price: "₹1,699", image: "/Product/photo.jpg", category: "necklaces", description: "A selection of fine necklaces made for easy layering." },
  { slug: "rose-crystal-watch", name: "Rose Crystal Watch", price: "₹2,899", image: "/Product/watch 2.jpg", category: "watches", description: "A rose dial crystal watch paired with slim bracelets." },
  { slug: "emerald-chain-watch", name: "Emerald Chain Watch", price: "₹2,999", image: "/Product/watch 3.jpg", category: "watches", description: "An emerald dial watch with bold chain inspired details." },
  { slug: "emerald-butterfly-watch", name: "Emerald Butterfly Watch", price: "₹2,899", image: "/Product/watch 4.jpg", category: "watches", description: "An emerald watch styled with a crystal butterfly bracelet." },
  { slug: "emerald-charm-watch", name: "Emerald Charm Watch", price: "₹2,799", image: "/Product/watch4.jpg", category: "watches", description: "A square emerald dial watch with colourful charm accents." },
  { slug: "prism-charm-necklace", name: "Prism Charm Necklace", price: "₹1,599", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.54.jpeg", category: "necklaces", description: "A playful gold necklace with jewel toned drops and polished disc charms." },
  { slug: "solara-medallion-necklace", name: "Solara Medallion Necklace", price: "₹1,399", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.57 (1).jpeg", category: "necklaces", description: "A fine beaded chain centred with a warm crystal medallion." },
  { slug: "golden-confetti-necklace", name: "Golden Confetti Necklace", price: "₹1,449", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.57 (2).jpeg", category: "necklaces", description: "A delicate chain scattered with softly moving polished gold discs." },
  { slug: "tiny-bloom-necklace", name: "Tiny Bloom Necklace", price: "₹1,299", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.57.jpeg", category: "necklaces", description: "A minimal chain finished with a petite cluster of colourful blooms." },
  { slug: "crystal-teardrop-necklace", name: "Crystal Teardrop Necklace", price: "₹1,349", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.58 (1).jpeg", category: "necklaces", description: "A timeless teardrop crystal suspended from a slender gold chain." },
  { slug: "starlight-crystal-necklace", name: "Starlight Crystal Necklace", price: "₹1,349", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.58.jpeg", category: "necklaces", description: "A bright star inspired crystal pendant for effortless daily shine." },
  { slug: "pearl-halo-necklace", name: "Pearl Halo Necklace", price: "₹1,499", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.59 (1).jpeg", category: "necklaces", description: "A smooth pearl pendant framed by a sculptural golden halo." },
  { slug: "satin-bow-necklace", name: "Satin Bow Necklace", price: "₹1,499", image: "/Product/WhatsApp Image 2026-09-23 at 16.34.59.jpeg", category: "necklaces", description: "A fluid statement chain finished with an elegant sculpted bow." },
];

export const categories = [
  { slug: "earrings", label: "Earrings", image: "/images/earring_category.jpg", alt: "Gold earrings" },
  { slug: "bangles", label: "Bangles", image: "/images/bangle_category.jpg", alt: "Gold bangles" },
  { slug: "rings", label: "Rings", image: "/images/ring_category.png", alt: "Collection of gold rings" },
  { slug: "necklaces", label: "Necklaces", image: "/images/necklace_category.png", alt: "Layered gold necklaces" },
  { slug: "hip-chains", label: "Hip Chains", image: "/images/hipchain_category.png", alt: "Layered gold hip chains" },
  { slug: "bracelets", label: "Bracelets", image: "/images/bracelet_category.png", alt: "Gold chain and tennis bracelets" },
  { slug: "watches", label: "Watches", image: "/images/watches_category.png", alt: "Gold and leather watches" },
  { slug: "anklets", label: "Anklets", image: "/Product/img2.jpg", alt: "Gold anklet", showOnHome: false },
  { slug: "kids", label: "Kids Jewellery", image: "/Product/Anklets.jpg", alt: "Kids gold anklet", showOnHome: false },
];
